### ISSUE TITLE
Fix the tag manager list

### ISSUE THREAD

**Issue by lizard-52** [CMPUT301F23T01/Sigma-Blue#118]
Selecting the tags is impossible on a phone.
Currently, arrow key navigation is required to select multiple tags on a phone, using the emulator.
We can reuse the long item click for each list item in ViewListActivity.

**Comment by echeng-git** [comment]
After copying over the multiple item selection from ViewListActivity to TagManagerFragment, we can look into utilising a superclass that handles the two to clean things up.

**Comment by lizard-52** [comment]
Working on the refactor now
