### ISSUE TITLE
Tag text is melded with its color on reentry

### ISSUE THREAD

**Issue by echeng-git** [CMPUT301F23T01/Sigma-Blue#153]
![image](https://github.com/CMPUT301F23T01/Sigma-Blue/assets/90707245/9e727dc8-2b04-4818-9567-4b96be50c87c)

It should be noted that the text being shown is the ``tagText`` attribute for each Tag that is attached to the respective item.

# Reproduction
Assign an tag to an item, return from the details fragment, and click on the item again. The tag text should appear like this.

**Comment by waridh** [comment]
I think this is a DB issue, so I will try and fix this one
