### ISSUE TITLE
Tags have duplicates, and tags are highlighted after changing the tags on an item

### ISSUE THREAD

**Issue by echeng-git** [CMPUT301F23T01/Sigma-Blue#209]
# Issue 1

When selecting the tag in the tag manager, duplicate tags by name (and not by color) are allowed.
On press, both tags of the same name are highlighted.

# Issue 2

When pressing the back button on the tag manager after, tags applied to the item are highlighted in the details view and edit view when they should not be. 

## Replication

From the list view activity, click on an item with tags, then click the edit button, then click the + button on the tags slide, and then click back. Clicking confirm when you are on the tags slide resets the highlighted state of the tags on the item.

**Comment by lizard-52** [comment]
Found a fix for issue 2

**Comment by lizard-52** [comment]
@waridh are you still seeing these issues?

**Comment by waridh** [comment]
I saw issue one earlier today. Isn't it still there?

**Comment by lizard-52** [comment]
heck

**Comment by lizard-52** [comment]
Ok PR https://github.com/CMPUT301F23T01/Sigma-Blue/pull/220 should fix this
