### ISSUE TITLE
Object oriented analysis

### ISSUE THREAD

**Issue by waridh** [CMPUT301F23T01/Sigma-Blue#3]
# Object oriented analysis

We need to create CRC cards in the wiki for all types of classes that are going to be involved with the process.

# Components of the project

## User Profiles

**Comment by waridh** [comment]
I am adding a database class for the items in the wiki.

**Comment by waridh** [comment]
Figure out if we need to make classes for the filter and sort menu.

**Comment by waridh** [comment]
We are including super classes on the crc cards

**Comment by waridh** [comment]
#31

**Comment by waridh** [comment]
# Components of the project

## Item

## ItemList

## Tags

## Photographs

## Scanning

## User Profiles

**Comment by bpaul2** [comment]
Closing due to completion of CRC cards. View part 5 in wiki
