### ISSUE TITLE
Design the sorting system

### ISSUE THREAD

**Issue by waridh** [CMPUT301F23T01/Sigma-Blue#35]
# Design the sorting system

The sorting system has to be able to accommodate sorting items by:
- date
- description
- make
- estimated value
- user defined tags.

## Filter

We need to be able to filter the items by:
- Date range
- Description keywords
- Make

## Development
- [ ] #142

**Comment by waridh** [comment]
These are all methods that could be done via database query, but we'd have to do a reading if that is faster than adjusting the local copy. Maybe there is a benefit in doing the query directory on the database? (Better synchronization).

**Comment by Yunyang-Lu** [comment]
From the CRC card design aspect, I am assuming the sorting and filtering is done in two separated fragments, where each pops out from the main viewListActivity, according to the user interface design. Will name them as itemSortFragment, itemFilterFragment.
The implementation details are not decided, I'm just trying to suggest/figure out how these modules work.
