### ISSUE TITLE
Build the product backlog

### ISSUE THREAD

**Issue by waridh** [CMPUT301F23T01/Sigma-Blue#4]
# Build the product backlog

Need to finish making the product backlog. Currently, our backlog is following the format that was given as an example.

## TODO

Need to onboard everyone on to the expectations for this project board.

**Comment by waridh** [comment]
It looks like they want us to number our items. I don't know what that means quite yet, so I think that we should figure it out. Let's keep track of that information on this project board.

**Comment by waridh** [comment]
This card is a part of project part 2
#31

**Comment by bpaul2** [comment]
Closing due to completion of requirements.
