### ISSUE TITLE
Import the user stories into the board

### ISSUE THREAD

**Issue by waridh** [CMPUT301F23T01/Sigma-Blue#7]

**Comment by waridh** [comment]
After looking at the rubric from the previous year, I think that they want us to number the stories. In fact, we might have to number more than just that, it just seems unclear to me right now.

**Comment by bpaul2** [comment]
Once a story is assigned as an issue, it will be given an number corresponding to that issue. Can we just use that as the "story number" as well, or does it have to be somewhere more concrete, like the wiki?

**Comment by waridh** [comment]
I think we might need to be using the number that they placed by the user story. Here is an example from the previous group that they gave us.


![Image](https://github.com/CMPUT301F23T01/Sigma-Blue/assets/90401236/156aa537-fb7d-4482-88d0-2c9ee8fb51fe)

**Comment by bpaul2** [comment]
My current guess is that it could correspond to the story size of the given user story? Definately somehting we should bring up to the TA next meeting.

**Comment by waridh** [comment]
#31

**Comment by bpaul2** [comment]
Closing issue for now. All stories have been added to the project board along with details and story points
